// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBolFzL76eHoKyEmCmbIwcPAb9zZ7vNT-k',
    appId: '1:965316311315:web:feb596cd14b13f720402e6',
    messagingSenderId: '965316311315',
    projectId: 'safety-a2a21',
    authDomain: 'safety-a2a21.firebaseapp.com',
    storageBucket: 'safety-a2a21.firebasestorage.app',
    measurementId: 'G-K7E0DHCHJF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCla5AnWNa8XK0nnYs4-WT9NUxRkf2VsLo',
    appId: '1:965316311315:android:673a8130dfa3c3390402e6',
    messagingSenderId: '965316311315',
    projectId: 'safety-a2a21',
    storageBucket: 'safety-a2a21.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBolFzL76eHoKyEmCmbIwcPAb9zZ7vNT-k',
    appId: '1:965316311315:web:feb596cd14b13f720402e6',
    messagingSenderId: '965316311315',
    projectId: 'safety-a2a21',
    authDomain: 'safety-a2a21.firebaseapp.com',
    storageBucket: 'safety-a2a21.firebasestorage.app',
    measurementId: 'G-K7E0DHCHJF',
  );
}
